#!/bin/bash
if [ "$1" == "" ]; then
  echo "usage: 0x0 <file or url>"
  exit
fi

echo "* Uploading: $1"

if [[ $1 =~ ^https?:// ]]
then
  form="url=$1"
else
  form="file=@$1"
fi

curl --progress-bar -F"$form" https://0x0.st | cat
