#!/usr/bin/env ruby
require 'rubygems'
require 'epitools'

IO.popen("apt-cache show #{ARGV * ' '}", "r") do |apt|
  lesspipe(:wrap=>true) do |less|
    separator = ("#"*50).light_cyan
  
    result = apt.read.
      gsub("\n\n") {|m| "\n\n#{separator}\n\n" }.
      gsub(/^\S+:/) { |m| m.light_yellow }
      
    less.puts "\n#{separator}\n\n#{result}"
  end
end
