#!/bin/bash

echo "* apt-get optimizing..."

sudoifnotroot dpkg --clear-avail

if [ ! "`which sync-available`" == "" ]; then
  sudoifnotroot sync-available
else
  echo "* dctrl-tools not installed. skipping sync-available."
fi

echo "* apt-get update..."
sudoifnotroot apt-get update > /dev/null

echo "* done!"
