#!/usr/bin/env ruby
require 'epitools'

pattern = Regexp.new( "(" + ARGV.map{|arg| Regexp.escape arg}.join("|") + ")" )

IO.popen("apt-cache search #{ARGV * ' '}", "r") do |apt|
  for line in apt
    lesspipe { |less| less.puts line.highlight(pattern) }
  end
end
