#!/bin/bash

KEYSERVER=keyserver.ubuntu.com

if [ "$#" == "0" ]; then
 echo "usage: apt-key-get [key-IDs...]"
else
  while (( "$#" )); do
    echo "+ Getting key $1 from $KEYSERVER..."
    #gpg --keyserver subkeys.pgp.net --recv $1 && gpg --export --armor $1 | sudo apt-key add -
    sudoifnotroot apt-key adv --keyserver $KEYSERVER --recv-keys "$1"
    shift
  done
fi

