#!/usr/bin/env ruby
#require 'shellwords'

#things = STDIN.read.lines.map(&:strip)

things = Dir["#{ENV["HOME"]}/mp3*/*"]
#p things.size

ignore = ["[Talks, Audiobooks]"]
things.reject! { |thing| ignore.any? { |ign| thing[ign] } }

amount = (ARGV.first || "10").to_i

cmd = %w[audacious -e] + (things - ignore).sample(amount)

system(*cmd)
