#!/bin/bash

error() {
  if [ "$1" != "" ]; then echo "Error: $@"; echo; fi

  echo "usage: areacode <3-digit north american area code>"
  exit 1
}

if [ "$1" == "" ]; then error "No area code supplied"; fi
if [[ ! "$1" =~ ^[2-9][0-9]{2}$ ]]; then error "Area code must be a 3-digit number"; fi

wp "Area code $1"
