#!/usr/bin/env ruby
########################################################
require 'epitools'

gem 'slop', "~> 3.6"
require 'slop'
########################################################



########################################################
# Parse options

opts = Slop.parse(help: true, strict: true) do
  banner "Usage: asn <host(s), url(s), or ip address(es)>"
end

args = ARGV

if args.empty?
  puts opts
  exit 1
end

########################################################

args.each do |arg|

  case arg
  when %r{(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})}
    ip = $1
  when %r{^(?:https?|ftp|gopher)://(.+)/$}, %r{(\w+\.\w+)}
    host = $1.gsub(/:\d+$/, '')
    puts "<8>[<9>+<8>] <7>Resolving <15>#{host}<7>...".colorize
    ip = Resolv.getaddress(host)
  else
    puts "Error: don't recognize #{arg}"
  end

  puts "<8>[<3>-<8>] <7>IP address is <15>#{ip}".colorize

  begin
    reversehost = Resolv.getname(ip)
    puts "<8>[<3>-<8>] <7>Reverse host is <15>#{reversehost}".colorize
  rescue Resolv::ResolvError
  end


  puts "<8>[<9>+<8>] <7>Looking up BGP info...".colorize

  result = IO.popen(["bgpview-cli", "ip", ip], &:read)
  puts
  puts result.gsub(/^(\s*\w+): (.+)$/) { "<3>#{$1}: <11>#{$2}" }.colorize

end
