#!/usr/bin/env ruby

require 'shellwords'

# Array of [ [dirname, path], ... ]
raw_mp3s = Dir["#{ENV["HOME"]}/mp3*/*"] + Dir["#{ENV["HOME"]}/mp3*/\\[offline*\\]/*"]
paths = raw_mp3s.
          reject { |e| e =~ /\.\w{1,4}$/ unless e =~ /\.(xspf|m3u8?)$/ }.
          map {|path| [path.split("/").last, path] }.
          sort_by {|path| path.first.downcase }


paths =
  paths.sample(10) +  # Random albums
  [["-"*50,nil]] +    # ASCII horizontal line
  paths

names = paths.to_h

path =
  IO.popen(%w[dmenu -l 40 -i -b -p Album:], "r+") do |f|
    f.puts names.keys.join("\n")
    f.close_write

    picked = f.gets.strip
    names[picked]
  end

EXTS = %w[
  mp3 m4a flac ogg wma fla flv mp2
]

AUDIO_RE = /\.#{Regexp.union EXTS}$/

# expanded =
#   Dir.open(path).
#   drop(2).
#   map { |filename| File.join(path, filename) }.
#   select { |fullpath| File.directory?(fullpath) || fullpath =~ AUDIO_RE }

# # require 'pp'; pp expanded
# exec("audacious", *expanded)

files = Dir["#{Shellwords.escape path}/**/*.{#{EXTS.join(",")}}"]
exec("audacious", *files)
