#!/usr/bin/env ruby

# Array of [ [dirname, path], ... ]
paths = Dir["#{ENV["HOME"]}/mp3*/*"].
          reject { |e| e =~ /\.\w{1,4}$/ }.
          map {|path| [path.split("/").last, path] }.
          sort_by(&:first)

# Prepend some random albums
paths = paths.sample(10) + [["-"*50,nil]] + paths


names = Hash[ paths ]

IO.popen(%w[dmenu -l 40 -i -b -p Album:], "r+") do |f|
  f.puts names.keys.join("\n")
  f.close_write

  picked = f.gets.strip
  path   = names[picked]
  
  system("audacious", path)
end
