#!/usr/bin/env ruby

# Array of [ [dirname, path], ... ]
paths = Dir["#{ENV["HOME"]}/mp3*/*"].
          reject { |e| e =~ /\.\w{1,4}$/ unless e =~ /\.(xspf|m3u8?)$/ }.
          map {|path| [path.split("/").last, path] }.
          sort_by {|path| path.first.downcase }


paths = 
  paths.sample(10) +  # Random albums
  [["-"*50,nil]] +    # ASCII horizontal line
  paths

names = Hash[paths]

path = 
  IO.popen(%w[dmenu -l 40 -i -b -p Album:], "r+") do |f|
    f.puts names.keys.join("\n")
    f.close_write

    picked = f.gets.strip
    names[picked]
  end

EXTS = %w[
  mp3 m4a flac ogg wma fla flv mp2
]

expanded = 
  Dir.open(path).
  drop(2).
  map { |filename| File.join(path, filename) }.
  select { |fullpath| File.directory?(fullpath) || fullpath =~ /\.#{Regexp.union EXTS}$/ }

# require 'pp'; pp expanded
exec("audacious", *expanded)
