#!/bin/bash

get_backlight() {
  echo "Current backlight: $(xbacklight -get)%"
}

if [ "$1" == "" ]; then
  get_backlight
  echo
  echo "usage: light <backlight brightness, 1-100>"
  exit 1
fi

if (( $1 < 1 || $1 > 100 )); then
  echo "brightness must be between 1 and 100"
  exit 1
fi

xbacklight -set "$@"
get_backlight
