#!/usr/bin/env ruby
require 'epitools'

BBSES = %{
  bbs.electronicchicken.com
  bbs.thebrokenbubble.com
  bbs.pharcyde.org
  bbs.diskshop.ca
}.nice_lines.map(&:strip)


def telnet(host)
  puts
  puts "Connecting to #{host}..."    

  exec("cp437", "telnet", host)
end  

def parse_choice(str)
  str = str.strip

  if str =~ /^(\d+)$/
    BBSES[$1.to_i - 1]
  elsif str.blank?
    nil
  else
    str
  end
end


if arg = ARGV.first

  if host = parse_choice(arg)
    telnet host
    exit
  else
    puts "<12>#{arg} <8>isn't a valid choice. Try again.".colorize
    puts
  end

end


BBSES.each.with_index do |option, i|
  puts "<15>#{i+1}<8>. <#{i+9}>#{option}".colorize
end
  
puts

loop do
  print "<15>pick<12>> ".colorize
  host = parse_choice STDIN.gets
  break if host
end

telnet host
      
