#!/bin/bash
BM_FILE=~/docs/bookmarks.txt
if [ "$1" == "" ]; then
  echo "$(cb)" | tee -a "$BM_FILE"
else
  if [[ "$1" =~ ^/([^/]+)/$ ]]; then
    query="${BASH_REMATCH[1]}"
    grep --color -i "$query" "$BM_FILE"
  else
    echo "$@" | tee -a "$BM_FILE"
  fi
fi
