#!/bin/bash
BM_FILE=~/docs/bookmarks.txt

if [ "$1" == "" ]; then
  LINE="$(cb)"
else
  if [[ "$1" =~ ^/([^/]+)/$ ]]; then
    query="${BASH_REMATCH[1]}"
    grep --color -i "$query" "$BM_FILE"
    exit
  else
    LINE="$@"
  fi
fi

echo "$LINE" | gsub -f "\n(?!\z)" -t "\\n" | tee -a "$BM_FILE"
