#!/bin/bash
unset CC CFLAGS CXX CXXFLAGS MAKE PARAMS

PROCESSORS="`cat /proc/cpuinfo|grep "processor"|wc -l`"

CONFIGFILE=buildconfig
MAKE="make -j`expr $PROCESSORS + 2`"
PARAMS=""

if [ -f $CONFIGFILE ]
then
   echo "==================== Loading parameters... ======================"
   . $CONFIGFILE
fi

export CC CFLAGS CXX CXXFLAGS MAKE PARAMS

echo ""
echo " Procssors: $PROCESSORS"
echo ""
echo " ====== Parameters: ==========================="
echo "            CC=$CC"
echo "        CFLAGS=$CFLAGS"
echo "           CXX=$CXX"
echo "      CXXFLAGS=$CXXFLAGS"
echo "          MAKE=$MAKE"
echo "        PARAMS=$PARAMS"
echo ""

if [ -f configure ]
then
   echo "============================ Configuring... ==============================="
   if ./configure $PARAMS
   then
      echo "============================ Making... =================================="
      eval $MAKE
      echo "========================= DONE! =============================="
   else
      echo "===================== Configure failed! ========================"
   fi
elif [ -f Rakefile ]
then
   echo "========================= Raking Build =============================="
   rake build
fi
