#!/bin/bash
if [ ! "$*" == "" ]
then
  DIR="$*"
  cd "$DIR"
else
  DIR="`pwd`"
fi

echo "* $DIR/CACHEDIR.TAG"

cat > CACHEDIR.TAG <<END
Signature: 8a477f597d28d172789f06886806bc55
# This file is a cache directory tag created by (application name).
# For information about cache directory tags, see:
#       http://www.brynosaurus.com/cachedir/
END
