#!/bin/bash

# CREATE TABLE songs (
#   /* Metadata from taglib */
#   title TEXT,
#   album TEXT,
#   artist TEXT,
#   albumartist TEXT,
#   composer TEXT,
#   track INTEGER,
#   disc INTEGER,
#   bpm REAL,
#   year INTEGER,
#   genre TEXT,
#   comment TEXT,
#   compilation INTEGER,

#   length INTEGER,
#   bitrate INTEGER,
#   samplerate INTEGER,

#   /* Information about the file on disk */
#   directory INTEGER NOT NULL,
#   filename TEXT NOT NULL,
#   mtime INTEGER NOT NULL,
#   ctime INTEGER NOT NULL,
#   filesize INTEGER NOT NULL,
#   sampler INTEGER NOT NULL DEFAULT 0, 
#   art_automatic TEXT, 
#   art_manual TEXT, 
#   filetype INTEGER NOT NULL DEFAULT 0, 
#   playcount INTEGER NOT NULL DEFAULT 0, 
#   lastplayed INTEGER, 
#   rating INTEGER, 
#   forced_compilation_on INTEGER NOT NULL DEFAULT 0, 
#   forced_compilation_off INTEGER NOT NULL DEFAULT 0, 
#   effective_compilation NOT NULL DEFAULT 0, 
#   skipcount INTEGER NOT NULL DEFAULT 0, 
#   score INTEGER NOT NULL DEFAULT 0, 
#   beginning INTEGER NOT NULL DEFAULT 0, 
#   cue_path TEXT, 
#   unavailable INTEGER DEFAULT 0, 
#   effective_albumartist TEXT, 
#   etag TEXT, 
#   performer TEXT, 
#   grouping TEXT
# );


if [ "$1" == "" ]; then
  DB=~/.config/Clementine/clementine.db
else
  DB="$1"
fi

sqlite3 "$DB" "select rating, playcount, artist, album, title, filename from songs where rating > 0 order by rating;"
