#!/usr/bin/env ruby

clipboards = {
  "clipboard" => "'Clipboard' clipboard (XA_CLIPBOARD)",
  "primary"   => "Primary clipboard (XA_PRIMARY)",
  "secondary" => "Secondary clipboard (XA_SECONDARY)",
}

if ARGV.include?("-c")
  puts '### Clipboards cleared! ########'
  puts
  for name, title in clipboards
    system("xclip", "-selection", name, "-i", "/dev/null")
  end
end

for name, title in clipboards
  puts "== #{title} ================="
  result = `xclip -o -selection #{name}`
  p result
  puts
end
