#!/usr/bin/env ruby

if ARGV.any?
  case ARGV.first
    when %r{^svn://}
      cmd = %w[svn checkout] + ARGV
    when %r{^git://}, %r{^\S+@\S+:\S+}, %r{^[^\/\s]+/[^\/\s]+}
      cmd = %w[git clone] + ARGV
    else
      puts "Unrecognized repository: #{ARGV.first}"
      exit 1
  end
  
  if cmd
    puts "Executing: #{cmd.join ' '}"
    system(*cmd)
  else
    puts "Uh oh! cmd didn't get set."
    exit 2
  end
  
else
  puts "usage: clone <repository url>"
end
