#!/usr/bin/env ruby
#
# Reads from STDIN or files, and counts how many copies of a line occur.
#

counts = Hash.new { |h,k| h[k] = 0 }

ARGF.each{ |line| counts[line] += 1 }

for k,v in counts.to_a.sort_by { |k,v| v }
  puts "#{v.to_s.rjust(5)}: #{k}"
end
