#!/bin/bash

BASE_PATH="/var/lib/denyhosts"

if [ "$1" == "" ]; then
  echo "usage: denyhosts-unban <ip address>"
  exit 1
else
  IP="$1"
fi

/etc/init.d/denyhosts stop

cd $BASE_PATH

for i in hosts hosts-restricted hosts-root hosts-valid users-hosts /etc/hosts.deny
do
  echo "- Removing $IP from $i..."
  mv $i $i.bak
  grep -v "$IP" $i.bak > $i
done

/etc/init.d/denyhosts start

echo "* Done"
