#!/usr/bin/env ruby
require 'epitools'

class String
  def url?
    !!(self =~ %r{^https?://.+/.+})
  end
end

def despam(link)
  URI.parse(link).params.values.map do |val|
    if val.url?
      val
    elsif (decoded = val.from_base64).url?
      decoded
    else
      nil
    end
  end.compact
end

if $0 == __FILE__

  args = ARGV

  if args.empty?
    print "Paste link: "
    args << gets.strip
  end

  if args.any?
    args.each do |arg|
      puts "Extracted links:"
      links = despam(arg)

      if links.any?
        links.each { |link| puts "\t#{link}" }
      else
        puts "\tnone found"
      end

    end
  end

end
