#!/usr/bin/env ruby
require 'epitools'

class String
  def url?
    !!(self =~ %r{^https?://.+/.+})
  end
end

def despam(link)
  URI.parse(link).params.values.map do |val|
    if val.url?
      val
    elsif (decoded = val.from_base64).url?
      decoded
    else
      nil
    end
  end.compact
end

def show_links_for(url)
  puts "Extracted links:"
  links = despam(url)

  if links.any?
    links.each { |link| puts "\t#{link}" }
  else
    puts "\tnone found"
  end
end

if $0 == __FILE__

  args = ARGV

  if args.empty?
    loop do
      print "Paste link: "
      url = gets.strip
      
      show_links_for url
      puts
    end
  end

  if args.any?
    args.each do |arg|
      show_links_for arg
    end
  end

end
