#!/usr/bin/env ruby

require 'rubygems'
require 'epitools'

# oss-linux: /usr/lib/oss/include/internals/timestamp.h
# linux-headers-2.6.35-23: /usr/src/linux-headers-2.6.35-23/Documentation/networking/timestamping/Makefile
# libpam-modules: /lib/security/pam_timestamp.so
# libpam-modules: /usr/share/man/man8/pam_timestamp_check.8.gz

pattern = Regexp.new( "(" + ARGV.map{|arg| Regexp.escape arg}.join("|") + ")", Regexp::IGNORECASE )

lesspipe(:wrap=>true) do |less|

  last_pkg = nil

  IO.popen("dpkg -S #{ARGV.join ' '} | sort", "r") do |results|
  
    for line in results
      if line =~ /^(\S+): (.+)$/
        pkg = $1
        path = $2

        if last_pkg != pkg
          less.puts pkg.light_blue + ":".light_black
        end
        less.puts "\t#{ path.highlight pattern }"
        
        last_pkg = pkg        
      else
        puts line
      end
    end
    
  end    
end

