#!/usr/bin/env ruby
require 'epitools'
require 'open-uri'

query = ARGV.join("+")
uri = "http://api.duckduckgo.com/?q=#{query.urlencode}&format=json"
result = open(uri).read.from_json

lesspipe(wrap: true) do |less|
  less.puts uri
  less.puts result

  def puts_if(thing)
    less.puts thing if thing
  end

  less.puts "<1>### <15>Searching for: <14>#{query} <1>###################".colorize
  less.puts

  if definition = result["Definition"] and !definition.blank?
    less.puts "<11>>> <14>#{definition}".gsub(" definition: ", "<8>: <7>").colorize
    less.puts
  end

  if abstract = result["Abstract"] and !abstract.blank?
    less.puts "<15>Abstract: <7>#{abstract}".colorize
  end

  result["RelatedTopics"].each do |related|

    if topics = related["Topics"]

      less.puts "<8>== <11>#{related["Name"]} <8>==".colorize
      less.puts
      topics.each do |topic|
        less.puts "  <3>* <7>#{topic["Text"]} <8>(<9>#{topic["FirstURL"]}<8>)".colorize
      end
      less.puts

    elsif text = related["Text"]
      less.puts "<9>* <7>#{text}".colorize
      less.puts
    end

  end

end
