#!/usr/bin/env ruby

def convert(input)
  output = input + ".wav"
  puts "* Converting #{input.inspect} to #{output.inspect}..."
  puts
  system("mplayer -vo null -ao pcm:waveheader:fast:file=\"#{output}\" \"#{input}\"")
  puts
end

unless ARGV.any?
  puts "usage: dumpwav <video file>"
  puts "effect: create a .wav file from the audio from the video."
else
  ARGV.each { |arg| convert arg }
end

