#!/usr/bin/env ruby
################################################################
gem 'slop', "~> 3.6"
require 'slop'
require 'epitools'
################################################################

################################################################
# Utility functions

def parse_opts_and_args
  opts = Slop.parse(help: true, strict: true) do
    banner 'Usage: dupes [options] <files or dirs to check for dupes...>'

    on 'd',  'delete',      'Delete dupes (keeping the oldest)'
    on 'i',  'interactive', 'Interactively delete dupes'
    on 'a',  'all',         "Process all files (don't ignore .git)"
    on 'e=', 'exclude',     'Exclude a path'
  end
  [opts, ARGV]
end

def title(msg); puts "<8>* <15>#{msg}".colorize; end
def subtitle(msg); puts "  <8>|_ <7>#{msg}".colorize; end

def common_prefix(files)
  x, *xs = files.map &:to_s

  x.each_char.with_index do |c, i|
    unless xs.all? { |s| s[i] == c }
      return x[0...i]
    end
  end

  ""
end

def trash(*paths)
  @trasher = Path.which("trsh", "rm").compact.first
  system(@trasher, "-v", *paths)
end

################################################################
# Parse args

opts, args = parse_opts_and_args
args << "." if args.empty?  # Default is current dir

################################################################
# Gather files

files = args.map do |arg|
  path = Path[arg]
  path.dir? ? path.ls_r.select(&:file?) : path
end.flatten

################################################################
# Exclude patterns
excludes = []
excludes << %r{/\.git/} unless opts[:all]
excludes << /#{Regexp.escape opts[:exclude]}/i if opts[:exclude]
excludes.each { |regex| files.reject! { |f| f =~ regex } }

################################################################
# Get file sizes
sized_files = files.map { |f| [f.size, f] }

title "Found <9>#{files.size}</9> files..."

################################################################
#
# Find duplicates by first grouping by file size,
# then grouping those groups by the file's SHA256 hash.
#
grouped_dupes = sized_files.group_by(&:first). # group by file size
  flat_map do |filesize, group|
    if group.size > 1
      group.group_by { |s,f| f.sha256 }.
      map { |sha,subgroup| subgroup.size > 1 ? subgroup : nil }.compact
    else
      nil
    end
  end.compact.sort


if grouped_dupes.empty?
  subtitle "no duplicates"
  exit 1
end

subtitle "#{grouped_dupes.size} duplicates"
puts


################################################################
if opts.delete?

  #
  # Delete all but oldest dupe
  #

  deleters = grouped_dupes.map do |group|
    keeper = group.sort_by { |size, path| path.mtime }.first
    (group - [keeper]).map { |size, path| path }
  end.flatten

  trash *deleters

elsif opts.interactive?

  #
  # Interactively delete duplicates
  #

  grouped_dupes.each do |group|

    prefix = common_prefix(group.map(&:last))

    group.each_with_index do |(size, file), i|
      puts "<7>#{i+1}<8>) <9>#{size.commatize} <8>| <11>#{file.relative_to(prefix)}".colorize
    end

    print "which to keep? (ENTER to skip) > "
    choice = $stdin.gets.strip

    # Skip this if the user enters a blank line
    if choice.blank?
      puts "Skipping"
      puts
      next
    end

    # Re-prompt if the user didn't pick a valid option
    unless group[choice.to_i-1]
      puts "Invalid choice."
      puts
      redo
    end

    keep = choice.to_i-1

    # Trash everything except the user's choice
    group.each_with_index do |(size, fn), i|
      trash(fn) unless i == keep
    end

    puts
  end

else

  #
  # Display duplciates without deletin' nothin'
  #
  grouped_dupes.each do |group|
    group.each do |size, file|
      puts "<9>#{size.commatize} <8>| <11>#{file.relative_to(Path.pwd)}".colorize
    end
    puts
  end

end
