#!/usr/bin/env ruby
require 'rubygems'
require 'epitools'

#VALID_EXTS = %w[avi asf wmv mp4 ogm mkv flv]

def extract_audio(infile)

  infile = Path[infile]
  
  p infile
  
  unless infile.exists?
    STDERR.puts "Couldn't find #{infile}"
    return
  end

  #unless VALID_EXTS.include? infile.ext
  #  STDERR.puts "Unrecognized video format: #{infile.ext}"
  #  return
  #end
  
  if infile =~ %r{^/dev/fd/}
    outfile = Path.pwd/"#{infile.filename}.mp3" 
  else    
    outfile = infile.with(:ext=>"mp3")
  end

  if outfile.exists?
    puts "Error: #{outfile} exists!"
    return
  end    
  
  puts
  puts "Input:  #{infile}"
  puts "Output: #{outfile}"
  puts
  
  # -lameopts q=5
  cmd = %w[mencoder -of rawaudio -oac mp3lame -ovc copy -o] + [outfile.to_s, infile.to_s]
  system(*cmd)
  
end

if ARGV.empty?
  puts "usage: extract-audio [video files]"
  puts "effect: Create an .mp3 from the audio of each video file."
else
  ARGV.each { |arg| extract_audio arg }
end
