#!/bin/bash

# download latest foobar-portable to ~/.foobar2000
FBHOME=~/.foobar2000
  FBFN=foobar2000-portable-latest.zip
 FBURL=http://chris.ill-logic.com/files/$FBFN

if [ ! -d "$FBHOME" ]; then
  echo
  echo "~/.foobar2000 not found... download?"
  echo "YES...."
  echo
  echo "#######################################"
  echo "DOWNLOADING FOOBAR2000 PORTABLE EDITION"
  echo "#######################################"
  echo
  mkdir "$FBHOME"
  wget -c $FBURL -O ~/.cache
  unzip ~/.cache/$FBFN "$FBHOME"
fi

echo "#####################################"
echo "LAUNCHING FOOBAR2000 PORTABLE EDITION"
echo "#####################################"
echo

echo "Starting tray alert daemon..."
#foo -n &

echo "Starting foobar2000..."
wine $FBHOME/foobar2000.exe

echo "Terminating tray alert daemon..."
#kill `jobs -p`
