#!/bin/bash
CMD="/usr/bin/fortune"

#FORTUNES="-e wisdom education science art work politics definitions law startrek"
FORTUNES=~/scripts/fortunes/

if [[ "$1" == "" ]]; then
  $CMD $FORTUNES
else
  $CMD $FORTUNES -i -m "$@"
fi
