#!/usr/bin/env ruby
#
#   TODOS:
# ----------------------------------------------
#   * show "remote" before "local"
#   * use slop
#     * -r removes (remote-)branch
#   * create remote branch (based on current?)
#   * prompt for confirmation when doing dangerous things
#     (or things that could be mistakes -- eg: creating a branch)
#   * eat ugly git messages and make them colourized and pretty 

#################################################################################
require 'epitools'
#################################################################################

class Branches

  attr_accessor :local, :remote, :current

  def initialize
    @local = []
    @remote = []
    @current = nil
  end
  
  def local?(branch); local.include? branch; end
  def remote?(branch); remote.include? branch; end
  def current?(branch); current == branch; end

  def print
  
    puts
    
    [ [:remote, :green], [:local, :yellow] ].each do |type, color|
      puts "<grey>== <light_white>#{type} branches: <grey>=============".colorize
      for branch in send(type)
        selected = (branch == current && type == :local)
        puts "   #{branch}".send(selected ? :bright_yellow : color)
      end
      puts
    end
    
  end
  
end

#################################################################################

def git_repo?
  path = Path.pwd
  loop do
    return true if (path/".git").dir?
    break unless path.dirs.pop
  end
  false
end

def ensure_git_repo
  unless git_repo?
    puts "Error: must be in a git repo."
    exit 1
  end
end

def get_branches
  ensure_git_repo
  
  branches = Branches.new
  
  `git branch -a`.lines.map(&:strip).each do |line|
    if line =~ %r{^\* (.+)$}
      line = $1
      branches.current = line
    end

    case line
    when /->/
      # ignore aliases
    when %r{^remotes/(.+)$}
      branches.remote << $1
    else 
      branches.local << line
    end
  end
  
  branches
end  

#################################################################################
## Main

args = ARGV

if args.empty?
  
  get_branches.print  
  
elsif args.first.in? ["--help", "-h"]
  
  puts %{usage: gb <branch name>

eg:
  gb existingbranch           => switch to existing branch         
  gb newbranch                => create a new branch
  gb origin/remotebranch      => create/checkout/track remote branch
  gb -p [<remote>]            => push current branch to remote (default: origin)
  gb -d branch                => delete local branch
  gb -d origin/branch         => delete remote branch
  gb -t [<remote>[/<branch>]] => track current branch on origin/<branchname> (or <remote>/<branchname>)
  gb -r <new_name>            => rename current branch to <new_name>
}
# TODO: 'gb -t' tracks current branch (git branch --set-upstream <branch> origin/<branch>)
# TODO: auto-stash uncommitted changes when switching branches, and auto-unstash when switching back.
# TODO: 'gb -r <dest>' renames current branch to <dest> (git branch -m <src> <dest>)

elsif args.first.downcase == "-d"
  ## Delete

  branches = get_branches

  args.shift
  branch = args.shift
  
  if branches.local? branch
    puts "<grey>* <light_cyan>Deleting <light_yellow>#{branch}".colorize
    system("git branch -D #{branch}")
  elsif branches.remote? branch
    if prompt("You sure you wanna delete a remote branch???".light_red, 'yN') == "y"
      puts
      puts "Okay!"
      puts
      
      remote, branch = branch.split("/")
      
      puts "<grey>* <light_cyan>Deleting <light_yellow>#{branch} <light_cyan>from <light_green>#{remote}".colorize
      
      system("git push #{remote} :#{branch}")
    else
      puts "Whew!".light_white
    end
  else
    puts "Unknown branch: #{branch}"
  end

elsif args.first.downcase == "-p"
  ## Push

  args.shift
  remote = args.shift || "origin"

  current = get_branches.current

  # Track if not already tracked
  system "git push #{remote} #{current}"

  args = ["-t"]

elsif args.first.downcase == "-t"
  ## Track
  branches = get_branches
  current = branches.current

  args.shift
  remote = args.shift || "origin"

  unless remote["/"]
    remote = "#{remote}/#{current}"
  end

  puts "<grey>* <light_yellow>#{current} <white>tracking <light_green>#{remote}".colorize
  system("git branch --set-upstream #{current} #{remote}")
else
  ## Branch
  branches = get_branches
  
  branch = args.first

  if branches.local? branch
    puts "<grey>* <light_white>Switching to <light_yellow>#{branch}".colorize
    system("git checkout #{branch}")
  elsif branches.remote? branch
    puts "<grey>* <light_white>Tracking <light_yellow>#{branch}".colorize
    system("git checkout --track #{branch}")
  else
    puts "* Creating new branch #{branch}"
    system("git branch #{branch}")
    system("git checkout #{branch}")
  end    
  
end
