#!/usr/bin/env ruby
require 'epitools'

COLORS = %w[
  blue
  red
  green
  yellow
  purple
  cyan
  grey/white
]

TYPES = ["", "-simple"]

# <see scripts/promptinfo for more info> 

puts "* Generating color scripts..."

for color, type in COLORS*TYPES

  back, fore = color.split('/')
  fore = "light_#{back}" unless fore

  path = Path["#{back}#{type}"]

  case type
  when "-simple"
    ps1 = "<grey>[<white>\\@<grey>] <grey>:: <#{fore}>\\w <white>$ "
  else
    ps1 = "<grey>[<white>\\@<grey>] <#{back}>\\u<grey>@<#{fore}>\\h <grey>:: <light_white>\\w <white>$ "
  end
  ps1 = ps1.colorize # colorize!
  ps1 = ps1.gsub(/((?:\e\[\d+m)+)/, "\\\[\\1\\\]") # mark ansi sections as "nonprinting"
  
  script = %{#!/bin/bash
#if [ "$TERM" == "xterm" -a "$COLORTERM" != "gnome-terminal" ]; then
#   export PROMPT_COMMAND='echo -ne "\\033]30;[`basename "$PWD"`]\\007"'
#fi
export PS1=#{ps1.inspect}
}

  next if path.exists? and prompt("Overwrite #{path}?") == 'n' 

  puts "  |_ #{path}"
  path.truncate
  path.write script
  path.chmod "+x"
  
end


