#!/usr/bin/env ruby
########################################################
require 'epitools/path'

gem 'slop', "~> 3.6"
require 'slop'
########################################################
#
# TODOs:
# - leave the README
#
########################################################
# Parse options

opts = Slop.parse(help: true, strict: true) do
  banner "Usage: git-rm-history [options]"

  on "n",  "dryrun",  "Just show what'll happen"
  # on "b=", "blong",  "desc", default: ""
end

args = ARGV

########################################################

class Path
  def du
    IO.popen(["du", "-k", "-d", "0", path], &:read)
  end
end

paths = args.map(&:to_Path)

if paths.empty?
  puts "Error: must supply a path" # unless you're already in a git dir, ya git!
  puts opts
end

paths.each do |path|
  gitdir    = path/".git"
  gitconfig = gitdir/"config"

  raise "#{path} doesn't exist"                       unless path.dir?
  raise "#{path} has no .git dir (not a git repo)"    unless gitdir.dir?
  raise "#{gitdir} has no config file (weird)"        unless gitconfig.exists?

  before = path.du

  config = gitconfig.read
  
  # path.rm_R
  puts "[*] removing #{gitdir}"
  unless opts.dryrun?
    FileUtils.rm_rf(gitdir)
  end
  # path.mv("#{path.path.chomp("/")}-tmp")

  path.mkdir
  gitdir.mkdir
  gitconfig.write(config)
  
  path.cd do
    unless system("git", "init")
      raise "'git init' failed for some reason (?)"
    end
  end

  after = path.du

  puts "Before: #{before}"
  puts " After: #{after}"
end