#!/bin/bash

#
# A list of keyservers: https://sks-keyservers.net/status/
#

#KEYSERVER=keyserver.ubuntu.com
#KEYSERVER=pgp.mit.edu            # slow!
#KEYSERVER=keys.openpgp.org       # missing keys
#gpg --keyserver $KEYSERVER --recv "$*"

# --keyserver isn't needed anymore; gpg now uses WKD by default (ie: --auto-key-locate local,wkd)
gpg --receive-keys "$@"
