#!/usr/bin/env ruby
greek_alphabet = %[
  Α α
  Β β
  Γ γ
  Δ δ
  Ε ε
  Ζ ζ
  Η η
  Θ θ
  Ι ι
  Κ κ
  Λ λ
  Μ μ
  Ν ν
  Ξ ξ
  Ο ο
  Π π
  Ρ ρ
  Σ σ/ς
  Τ τ
  Υ υ
  Φ φ
  Χ χ
  Ψ ψ
  Ω ω
].each_line.map(&:strip).reject(&:empty?)

greek_alphabet.each_with_index { |chars, i| puts "#{(i+1).to_s.rjust(2)}: #{chars}" }
