#!/usr/bin/env python
from nltk.parse.generate import generate
from nltk import CFG

grammar = """greeting -> g
  g -> w NP | NP
  w -> 'with'
  NP ->  AP NP | N c N | N
  c -> 'and'
  AP -> AvP A | A
  AvP -> 'truly' | 'very' | 'most' | 'extra'
  A -> 'best' |  'warmest' |  'greatest' | 'warm' |  'kind' |  'kindest' |  'extra'
  N -> 'wishes' |  'greetings' |  'regards' |  'cheers' |  'thanks' |  'tidings' |  'yours' | 'blessings'
  """

g = CFG.fromstring(grammar)

for sentence in generate(g, depth=6):
  print(sentence)
