#!/usr/bin/env ruby
require 'fileutils'

# TODO: Fix Path#/: If glob chars, but a file exists by that name, assume it's the file.

QUARTER_LABEL_REGEXP = /^(20|19)\d\d-Q\d$/

# fns = Dir["*"].select do |fn| 
#   not fn =~ /^(20\d\d-Q\d|group_by_date)$/
# end

class Time
  def quarter_label
    "#{year}-Q#{quarter}"
  end  

  def quarter
    (month / 3.0).ceil
  end
end

current_quarter = Time.now.quarter_label

files   = Dir["*"].reject { |fn| File.directory?(fn) and fn =~ QUARTER_LABEL_REGEXP }

grouped = files.group_by { |fn| File.mtime(fn).quarter_label }

grouped.sort.each do |quarter, files|
  next if quarter == current_quarter

  puts "#{quarter}"

  Dir.mkdir(quarter) unless File.directory? quarter

  files.each do |src|
    dest = File.join(quarter, src)
    # puts "#{src} => #{dest}"
    puts "  #{src}"
    # FileUtils.mv src, dest
    File.rename src, dest
  end

  puts
end

