#!/usr/bin/env ruby
require 'epitools'
require 'fileutils'

# TODO: Fix Path#/: If glob chars, but a file exists by that name, assume it's the file.

QUARTER_LABEL_REGEXP = /^(20|19)\d\d-Q\d$/

# fns = Dir["*"].select do |fn| 
#   not fn =~ /^(20\d\d-Q\d|group_by_date)$/
# end

class Time
  def quarter_label
    "#{t.year}-Q#{t.quarter}"
  end
end

current_label = Time.now.quarter_label



files = Dir["*"].reject { |path| path.filename =~ QUARTER_LABEL_REGEXP and path.dir?}

files.
    map       {|fn| [fn, File.mtime(fn)] }.
    select    {|fn,t| t.quarter_label != current_label }.
    group_by  {|fn, t|  }.
    each do |date, files|

  FileUtils.mkdir_p(date)

  p [:files, files.size, :date, date]
  files.each.with_index do |src, index|
    dest = File.join(date, src)
    p [:to, dest, :from, src]
    FileUtils.mv src, dest
  end
end

