#!/usr/bin/env ruby
require 'fileutils'

QUARTER_LABEL_REGEXP = /^((?:20|19)\d\d)-Q(\d)$/

class Time
  def quarter_label
    "#{year}-Q#{quarter}"
  end  

  def quarter
    (month / 3.0).ceil
  end

  def quarter_date
    Time.new(year, quarter * 3)
  end
end

current_quarter = Time.now.quarter_date
files           = Dir["*"].reject { |fn| File.directory?(fn) and fn =~ QUARTER_LABEL_REGEXP }
grouped         = files.group_by { |fn| File.mtime(fn).quarter_date }

# Move all the files to the appropriate directories
grouped.sort.each do |date, files|
  next if date == current_quarter # skip files in this quarter

  dir = date.quarter_label

  Dir.mkdir(dir) unless File.directory? dir

  puts "#{dir}"

  files.each do |src|
    dest = File.join(dir, src)
    # puts "#{src} => #{dest}"
    puts "  #{src}"
    # FileUtils.mv src, dest
    File.rename src, dest
  end

  puts
end

# Fix the modification times on the quarter directories
Dir["*"].each do |fn|
  if File.directory?(fn) and fn =~ QUARTER_LABEL_REGEXP
    qdate = Time.new($1.to_i, $2.to_i * 3)

    unless File.mtime(fn) == qdate
      puts "* Changing mtime on #{fn} => #{qdate}"
      File.utime(File.atime(fn), qdate, fn)
    end
  end
end
