#!/usr/bin/env ruby
require 'epitools'
require 'slop'

opts = Slop.new :help => true do
  banner "Usage: gsub -f from -t to [files...]"
  
  on :v, :verbose, 'Enable verbose mode'           
  on :n, :dryrun, 'Dry-run', false                  
  on :f, :from, 'From', :optional => false      
  on :t, :to, 'To', :optional => false  
end

opts.parse do |arg|
  path = Path[arg]

  puts "* gsubbing: #{path}"

  unless path.exists?
    puts "  |_ NOT FOUND."
    next
  end
  
  if path.size > 1.million
    answer = prompt("You sure you want to gsub a file that's #{path.size.commatize} bytes?")
    next unless answer == "y"
  end
  
  data = path.read
  changes = 0
  data.gsub! opts[:from] do |match|
    changes += 1
    opts[:to]
  end
  
  puts "  |_ #{changes} changes#{" would be" if opts.dryrun?} made"
  
  path.write(data) unless opts.dryrun?
end

