#!/bin/bash
#
# 'hdmi-audio-toggle' automagically switches pulseaudio output the best sink (HDMI or internal)
#

msg() {
  echo "$*"
  notify-send "$*"
}

CARD_PATH="/sys/class/drm/card0/"

# AUDIO_OUTPUT="analog-surround-40"
AUDIO_OUTPUT="analog-stereo"

for OUTPUT in $(cd "$CARD_PATH" && echo card*); do
  OUT_STATUS=$(<"$CARD_PATH"/"$OUTPUT"/status)
  if [[ $OUT_STATUS == connected ]]
  then
    echo "$OUTPUT connected"
    case "$OUTPUT" in
      "card0-HDMI-A-1")
        AUDIO_OUTPUT="hdmi-stereo" # Digital Stereo (HDMI 1)
     ;;
      "card0-HDMI-A-2")
        AUDIO_OUTPUT="hdmi-stereo-extra1" # Digital Stereo (HDMI 2)
     ;;
    esac
  fi
done

msg "HDMI output: $AUDIO_OUTPUT"
pactl set-card-profile 0 output:$AUDIO_OUTPUT+input:analog-stereo

## Use this if you're not the user who controls the pulse session
# PULSE_SERVER="unix:/run/user/"$USER_ID"/pulse/native"
# USER_NAME=$(who | awk -v vt=tty$(fgconsole) '$0 ~ vt {print $1}')
# USER_ID=$(id -u "$USER_NAME")
# sudo -u "$USER_NAME" pactl --server "$PULSE_SERVER" set-card-profile 0 output:$AUDIO_OUTPUT+input:analog-stereo
