#!/bin/bash

if [ "$1" == "" ]; then
  echo "usage: ipinfo"
  exit 1
fi

IP="$1"

if ! echo $IP | grep -E '([0-9]{1,3}\.?){4}' &> /dev/null
then
  IP=$(dig +short "$IP" | head -n1)
fi

if [ "$IP" == "" ]; then 
  echo "IP address not found"
  exit 1
fi

curl https://ipinfo.io/$IP