#!/bin/bash

if [ "$1" == "--help" ]; then
  echo "journal-cleanup trims the systemd journal to the desired size"
  echo
  echo "usage: journal-cleanup [<size, default: 500M>]"
  echo
  exit 1
fi

if [ "$1" == "" ]; then
  SIZE=500M
else
  SIZE=$1
fi

journalctl --vacuum-size=$SIZE
