#!/usr/bin/ruby

require 'rubygems'
require 'epitools'
require 'json'
require 'open-uri'
require 'awesome_print'

if ARGV.any?
  puts "Opening #{ARGV.first}..."
  input = open(ARGV.first)
else
  input = STDIN
end

json = JSON.parse(input.read)
lesspipe { |less| less.puts json.ai }
