#!/usr/bin/env ruby

running = `uname -r`.strip
package = "linux"

if running =~ /(.+)-([a-z]+)$/
  running = $1
  package += "-#{$2}"
end

if which("xbps-query")
elsif which("pacman")
  installed = `pacman -Qi #{package}`.each_line.grep(/Version/).first.strip.split(/\s+:\s+/).last
elsif which("dpkg")
  raise "doesn't work with debian... yet"
else
  raise "dunno which distro this is. please fix me!"
end

puts
puts "   Kernel: #{package}"
puts "  Running: #{running}"
puts "Installed: #{installed}"
puts

if installed == running
  puts "\e[32m\e[1mEverything is fine.\e[0m"
else
  puts "\e[31m\e[1mYou better reboot!\e[0m"
end

puts
