#!/usr/bin/env ruby
require 'io/console'

print "\e[?9h"

STDIN.raw do |io|
  loop do
    c = io.read 1
    if (28..127).include? c.ord
      print c
    else
      print c.inspect.gsub(/(^"|"$)/, '')
    end
    
    break if c == ?\C-c
  end
end

print "\e[?9l"
