#!/usr/bin/env ruby
require 'io/console'

print "\e[?9h"

STDIN.raw do |io|
  loop do
    c = io.read 1
    n = c.ord

    if (28..126).include? n
      s = c
    else
      s = c.inspect.gsub(/(^"|"$)/, '')
    end

    print "#{s} [#{n}] "    

    break if c == ?\C-c
  end
end

print "\e[?9l"
