#!/bin/bash

NUMFILES=25

if [ $(uname -s | grep -E '(Darwin|BSD)') ]
then
  CMD="gnuls"
else
  CMD="ls"
fi

# Sort by size
if [ "$1" == "-s" ]; then
  shift
  ARGS="-hlSr"

# Sort by time
else
  ARGS="-hltr"

fi

# Show all files
if [ "$1" == "-a" ]; then
  shift
  $CMD --color=force $ARGS "$@" | sed -r s/'^(\S+\s+){3}\S+'/''/ | less -R -X "+\\>"

# Show $NUMFILES files
else
  $CMD --color=force $ARGS "$@" | tail -n $NUMFILES | sed -r s/'^(\S+\s+){3}\S+'/''/
fi
