#!/bin/bash

if [ "$1" == "-s" ]; then
  # Sort by size
  shift
  ARGS="-hlSr"
else
  # Sort by time
  ARGS="-hltr"
fi

if [ "$1" == "-a" ]; then
  shift
  ls --color=force $ARGS "$@" | sed -r s/'^(\S+\s+){3}\S+'/''/ | less -R -X "+\\>"
else
  ls --color=force $ARGS "$@" | tail -n 15 | sed -r s/'^(\S+\s+){3}\S+'/''/
fi


