#!/usr/bin/env ruby
########################################################
require 'mhtml'
require 'epitools'

gem 'slop', "~> 3.6"
require 'slop'
########################################################

class Mhtml::RootDocument
  def file_path
    "index.html"
  end

  def each
    return to_enum(:each) unless block_given?

    yield self
    sub_docs.each { |sd| yield sd }
  end
end

########################################################
# Parse options

opts = Slop.parse(help: true, strict: true) do
  banner "Usage: mhtmldump [options] <mhtml file>"

  on "l",  "list",     "List documents in MHTML file"
  on "x",  "extract",  "Extract documents to (current or supplied) direcory"
  on "C=", "dir",      "Target directory (creates it if it doesn't exist)"
end

args = ARGV

if args.empty?
  puts "Error: You must specify the mhtml filename."
  puts
  puts opts
  exit 1
end

########################################################

mhtml_filename, *files = args

path  = Path[mhtml_filename]
mhtml = Mhtml::RootDocument.new(path.read)

if opts.list?
  puts "<8>* <15>Listing documents in <14>#{path.filename}<7>...".colorize

  mhtml.each do |doc|
    puts "  |_ <7>#{doc.file_path} <8>(<9>#{doc.body.size} <7>bytes<8>)".colorize
  end
else
  if opts[:dir]
    outdir = Path[opts[:dir]]
  else
    outdir = Path[path.basename]
  end

  if outdir.exists?
    puts "Error: #{outdir} already exists."
    exit 1
  end

  outdir.mkdir_p

  puts "<8>* <15>Extracting <11>#{path.filename} to <14>#{outdir}<7>...".colorize

  outdir.cd do
    mhtml.each do |doc|
      outfilename = CGI.escape(doc.file_path)
      puts "  <8>|_ <7>#{doc.file_path} <8>(<9>#{doc.body.size} <7>bytes<8>)".colorize
      open(outfilename, "wb") { |f| f.write(doc.body) }
    end
  end
end
