#!/bin/bash

echo "Make sure to open http://mitm.it/ (through the proxy server) to install certificates."

# --web-port PORT       Web UI port.
# --web-host HOST       Web UI host.
#mitmweb --no-web-open-browser --set tls_version_client_min=UNBOUNDED --listen-port 8118

#mitmproxy --set tls_version_client_min=UNBOUNDED --listen-port 8118

mitmdump --ssl-insecure --set tls_version_client_min=UNBOUNDED --listen-port 8118

