#!/usr/bin/env ruby

class Mount
  attr_accessor :dev, :path, :type, :options

  def initialize(line)
    @path, @dev, @type, @options = line.strip.split
    @options = @options.split(",")
  end

  def system?
    (path =~ %r{^/(sys|dev|proc|run/user|tmp)}) or dev == "systemd-1"
  end
  
  def inspect
    "#{type}: #{path} (#{dev})"
  end
  
  def to_s
    "  #{path} (#{dev})"
  end
end

mounts = IO.popen(["findmnt", "-l"]) { |io| io.drop(1).map { |line| Mount.new line } }

puts
mounts.reject(&:system?).group_by(&:type).each do |type, mounts|
  puts "== #{type} ======================"
  mounts.each { |mount| puts mount }
  puts
end
