#!/usr/bin/env ruby

class String
  def frontslashed
    (self[0] != '/') ? "/"+self : self
  end
end

class Mount
  attr_accessor :dev, :path, :type, :options

  def initialize(line)
    @path, @dev, @type, @options = line.strip.split(' ')
    @options = @options.split(",")
  end

  def system?
    (path =~ %r{^/(sys|dev|proc|run/user|tmp)}) or dev == "systemd-1"
  end
  
  def to_s
    "  #{path} (#{dev})"
  end
end

mounts = IO.popen(["findmnt", "--raw"]) { |io| io.drop(1).map { |line| Mount.new line } }

puts
mounts.reject(&:system?).group_by(&:type).each do |type, mounts|
  puts "== #{type} ======================"

  mounts.each do |mount|
    case type
    when "fuse.mergerfs"
      puts "* #{mount.path}"
      mount.dev.split(":").each { |src| puts "  |_ #{src.frontslashed}" }
    else
      puts mount
    end
  end

  puts
end
