#!/bin/bash

if [ "$1" == "" ]; then
  echo "Usage: nat <lan interface> <wan interface>"
  exit 1
fi

LAN_IF=$1
WAN_IF=$2

echo "Setting up NAT..."
echo "  LAN: $LAN_IF"
echo "  WAN: $WAN_IF"
echo

echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -o $WAN_IF -j MASQUERADE
iptables -A FORWARD -i $WAN_IF -o $LAN_IF -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $LAN_IF -o $WAN_IF -j ACCEPT
