#!/usr/bin/ruby
require "rexml/document" 

doc       = REXML::Document.new($<)
formatter = REXML::Formatters::Pretty.new

formatter.compact = true # use as little whitespace as possible
formatter.write(doc, $stdout)
$stdout.puts
