#!/bin/bash

## settings ###################
pre_accel_time=60
ms_between_movements=10
movements_before_acceleration_peaks=30
final_pixels_per_movement=30

# values range from approximately -600 to 600
acceleration_curve=100

runcmd() {
  echo "$@"
  "$@"
}

runcmd setxkbmap -option keypad:pointerkeys
runcmd xkbset mousekeysaccel $pre_accel_time $ms_between_movements $movements_before_acceleration_peaks $final_pixels_per_movement $acceleration_curve
runcmd xkbset exp mousekeys
runcmd xkbset mousekeys

echo
echo "Enabled! Press 'LeftShift+NumLock' to toggle it"

if [ -f ~/.xmodmap ]; then
  echo "(reloading ~/.xmodmap for good measure)"
  xmodmap ~/.xmodmap
fi
