#!/usr/bin/env ruby

ARGV.each do |arg|
  fork do
    # This nonsense is needed to totally squelch the STDOUT of the launched process.
    the_pwd = Dir.pwd
    Process.daemon
    Dir.chdir(the_pwd)
    exec("xdg-open", arg)
  end
end