#!/usr/bin/env ruby
# encoding: utf-8
require 'dbm'
###################################################################

CACHE_DIR = File.expand_path("~/.cache/oui")
DB_FILE   = File.join CACHE_DIR, "oui-database"

CSV_URL   = "http://standards-oui.ieee.org/oui/oui.csv"
# CSV_URL   = "oui.csv"

###################################################################
# Utility functions
###################################################################

def help!
  puts
  puts "Usage:"
  puts "  oui [options] <mac address(es)...>"
  puts
  puts "Options:"
  puts "  -u  Update the IEEE database of OUI MAC addresses"
  puts "      (from: #{CSV_URL})"
  puts
end

def db_exists?
  Dir["#{DB_FILE}*"].any?
end

def db_open(flags=DBM::READER)
  db = DBM.open(DB_FILE, 0666, flags)

  if block_given?
    result = yield db
    db.close
    result
  else
    db
  end
end

def backup(src)
  if File.exists? src
    counter = 1
    dest = "#{src}.bak"

    while File.exists? dest
      counter += 1
      dest = "#{src}.bak#{counter}"
    end

    puts "  |_ database backed up to: #{dest.inspect}"

    File.rename(src, dest)
  end
end

###################################################################
# Patches
###################################################################

module Enumerable
  def average
    any? ? reduce(:+) / size.to_f : 0
  end
end

class Numeric
  #
  # Convert this number to a string, adding commas between each group of 3 digits.
  #
  # (The "char" argument is optional, and specifies what character to use in between
  #  each group of numbers.)
  #
  def commatize(char=",")
    int, frac = to_s.split(".")
    int = int.gsub /(\d)(?=\d{3}+(?:\.|$))(\d{3}\..*)?/, "\\1#{char}\\2"

    frac ? "#{int}.#{frac}" : int
  end


  def humanize_bytes
    if self < 1024
      sprintf("%d bytes", self)
    elsif self < 1024 * 1000 # 1000kb
      sprintf("%0.1f kb", self.to_f / 1024)
    elsif self < 1024 * 1024 * 1000  # 1000mb
      sprintf("%0.3f mb", self.to_f / 1024 / 1024)
    else
      sprintf("%0.3f gb", self.to_f / 1024 / 1024 / 1024)
    end
  end

end

###################################################################
# Commands
###################################################################

def update

  require 'csv'
  require 'http'

  puts "* Re-importing database..."
  puts "  |_ source: #{CSV_URL.inspect}"

  backup(DB_FILE)

  db_open(DBM::NEWDB) do |db|

    response = HTTP.get(CSV_URL).body

    first_chunk  = Time.now
    chunks       = []
    bytes_loaded = 0

    while chunk = response.readpartial
      bytes_loaded += chunk.size
      # elapsed       = now - last_update
      total_elapsed = Time.now - first_chunk
      rate          = (bytes_loaded / total_elapsed)

      chunks << chunk

      # p elapsed: total_elapsed, chunk: chunk.size, rate: rate #, avg: avg_rate
      print "\e[1G  |_ bytes loaded: #{bytes_loaded.commatize} (#{rate.humanize_bytes}/sec)\e[J"
    end

    puts

    # CSV.new(open(CSV_URL), :headers => :first_row).each.with_index do |row, n|
    CSV.parse(chunks.join, :headers => :first_row).each.with_index do |row, n|
      # MA-L,34F968,"ATEK Products, LLC",210 NE 10th Avenue Brainerd MN US 56401
      type, hex, company, address = row.fields
      company.strip! if company
      address.strip! if address

      db[hex] = "#{company}\n#{address}"

      $stdout.print "\e[1G  |_ records imported: #{n.commatize}\e[J" if n % 3 == 0
      $stdout.flush
    end

    puts
    puts "* Done!"

  end

end

###################################################################

def lookup_macs(args)

  db_open do |db|
    args.map do |arg|
      prefix = arg.upcase.scan(/[0-9A-F]/).take(6).join

      if prefix.size < 6
        $stderr.puts "* Error: #{arg} is too short -- must be at least 6 chars (3 hex bytes)"
        next
      end

      result = db[prefix]
      result && result.split("\n")
    end
  end

end

###################################################################
# Main
###################################################################


if $0 == __FILE__

  Dir.mkdir CACHE_DIR unless File.exists? CACHE_DIR

  # Help
  if ARGV.include? "-h" or ARGV.include? "--help"
    help!

  # Update
  elsif ARGV.include? "-u"
    update

  # No database
  elsif not db_exists?
    puts "You must first download the OUI database. Run 'oui -u'."
    exit 1

  # No arguments
  elsif ARGV.empty?
    help!
    db_open { |db| puts "(OUI database currently has #{db.size} entries)" }

  # Display results
  else
    results = lookup_macs(ARGV)
    ARGV.zip(results).each do |arg, result|
      nicearg = arg.upcase.scan(/[0-9A-F\:\-]/).join
      if result
        company, address = result
        puts "#{nicearg} - #{company}"
        puts (" " * (nicearg.size+3)) + address if address
      else
        puts "#{nicearg} - not found"
      end
    end
  end

end
