#!/usr/bin/env ruby
gem "slop", "~> 3.6"
require 'slop'
require 'epitools'

def packages_that_depend_on(package)
  result = []

  [`pacman -Sii #{package}`, `pacman -Qi #{package}`].each do |output|
    output.each_line do |l|
      if l =~ /Required By\s+: (.+)/
        result += $1.strip.split unless $1["None"]
        break
      end
    end
  end

  result
end

for package in ARGV
  puts "<8>=== <14>#{package} <8>============".colorize
  puts

  packages = packages_that_depend_on(package)

  if packages.empty?
    puts "  <12>None".colorize
  else
    system "pacman", "-Ss", "^(#{packages.join '|'})$" # upstream packages
    system "pacman", "-Qs", "^(#{packages.join '|'})$" # packages that are only installed locally
  end

  puts
end
