#!/bin/bash
lesscmd="less -RXFi"
paccmd="pacman --color=always"

if [[ "$1" == "" ]]; then
  $paccmd -Q | $lesscmd
else
  if $paccmd -Ql "$*" 2>&1
  then
    # yay it worked
    echo
  else
    echo
    echo "== Similar packages ==="

    $paccmd -Q | grep --color=always "$*"
  fi | $lesscmd
fi

