#!/usr/bin/env ruby
################################################################
require 'digest'
require 'zlib'
################################################################

module Digest
  class CRC32 < Digest::Class
    def initialize
      reset
    end

    def reset
      @crc = 0
    end

    def update(str)
      @crc = Zlib::crc32_combine(@crc, Zlib::crc32(str), str.size)
    end
    alias << update

    def digest_length; 4; end
    def finish; [@crc].pack("N"); end
  end
end

################################################################

HASHERS = {
  "--crc"    => Digest::CRC32,
  "--md5"    => Digest::MD5,
  "--sha1"   => Digest::SHA1,
  "--sha256" => Digest::SHA256,
  "--sha512" => Digest::SHA512,
}

################################################################

BLOCKSIZE=2**16 # 64k read size

################################################################

def usage
  puts "Usage:"
  puts "  pipesum [options...]"
  puts
  puts "Purpose:"
  puts "  Insert this into a pipeline to hash data on the fly, and output"
  puts "  the computed hash(es) to STDERR."
  puts
  puts "Options:"
  puts "  --all     => Compute all hash functions"
  HASHERS.each do |opt, klass|
    puts "  #{opt.ljust(9)} => #{klass}"
  end
  puts
  puts "(Note: Defaults to --sha1 if no options specified)"
  puts
  puts "Example:"
  puts "  curl http://hostname.website/file.iso | pipesum --sha1 > file.iso"
  puts
end

################################################################

opts, args = ARGV.partition { |arg| arg[/^--?\w/] }

if opts.delete("--help") or opts.delete("-h")
  usage
  exit
end

opts += ["--md5", "--sha1", "--sha256"] if opts.empty?

if opts.delete("--all")
  opts += HASHERS.keys
end

################################################################

def sum(digests, input, output=nil, messages=$stderr)
  while data = input.read(BLOCKSIZE)
    digests.each {|digest| digest << data }
    output.write(data) if output
  end

  digests.each do |digest|
    algo = digest.class.to_s.split("::").last
    messages.puts "#{algo.rjust(9)}: #{digest}"
  end

  output.close if output
end

def create_digests(opts)
  opts.uniq.map do |opt|
    if klass = HASHERS[opt]
      klass.new
    else
      puts "Unrecognized option: #{opt}"
      exit 1
    end
  end
end

require 'epitools'

if args.any?
  args.each do |arg|
    # puts "=== #{arg} ========================================="
    puts arg

    digests = create_digests(opts)

    begin
      open(arg, "rb") { |f| sum(digests, f, nil, $stdout) }
    rescue => e
      puts "   #{e.inspect}"
    end

    puts
  end
else
  sum(create_digests(opts), $stdin, $stdout)
end
