#!/usr/bin/env python2
from BitTorrent import bencode
import os, sys
fn = sys.argv[1]

print "Reading", fn
t = bencode.bdecode( open(fn).read() )

print "Setting private..."
t['info']['private'] = 1

print "Making backup..."
os.rename(fn, fn+".backup")
print "Writing..."
open(fn,"wb").write(bencode.bencode(t))

print "Done!"
