#!/usr/bin/env ruby
require 'epitools'

class Path

  def in_tree?(filename)
    p = Path.pwd
    while p.dirs.any?
      return true if (p/filename).exists?
      p.dirs.pop
    end
    false
  end

end

## args

if ARGV.any? 
  targets = ARGV
else
  targets = ['.']
end


## checkout every arg

for target in targets

  case target
  when %r{^git://}, %r{^https://.+\.git}, %r{\S+@\S+:\s+\.git}
  
    cmd = ["git", "clone", target]
    
    puts
    puts "=== Cloning #{target} ==="
    puts
    system(*cmd)
    
  else
  
    path = Path[target]

    if path.exists?
    
      if path.in_tree?(".git")
        cmd = "git pull"
      elsif path.in_tree?(".hg")
        cmd = "hg pull -u"
      elsif (path/".svn").dir?
        cmd = "svn update"
      elsif (path/"CVS").dir?
        cmd = "cvs update -dP"
      end
      
      puts
      puts "=== Updating #{target} (#{cmd}) === "
      puts
      system(cmd)
      
    else
      puts "* #{target.inspect} not found"
    end
    
  end
  
end


