#!/usr/bin/env ruby

def push_it_good(dir)
  Dir.chdir dir

  while Dir.pwd != "/"
    if File.directory? ".git"
      puts "* Pushing: #{Dir.pwd}"
      puts "  |_ remote: #{`git remote get-url --push origin`.strip}"
      print "  |_ "
      system("git", "push")
      return
    end
    Dir.chdir ".."
  end

  puts "* Dir: #{Dir.pwd}"
  puts "  |_ Bunko! No .git dir found"
end

if ARGV.any?
  dirs=ARGV
else
  dirs=["."]
end

# WARNING: Does not check "/.git"
for dir in dirs
  push_it_good(dir)
end
