#!/bin/bash
BIN="`which redshift-gtk gtk-redshift`"


# LOC="42.8142432:-73.9395687" # Toronto
# LOC="37.7576171,-122.5776844" # SF
LOC="42.8142432:-110.9395687" # Wyoming

# $BIN -t 6300:3400 -l 
$BIN -t 6300:3400 -l $LOC
# -t DAY:NIGHT	Color temperature to set at daytime/night
#
# The neutral temperature is 6500K. Using this value will not
# change the color temperature of the display. Setting the
# color temperature to a value higher than this results in
# more blue light, and setting a lower value will result in
# more red light.
#
# Default values:
#
#   Daytime temperature: 5500K
#     Night temperature: 3700K
