#!/usr/bin/env python
import readline, sys, os

if len(sys.argv) > 1:
  src = sys.argv[1]
else:
  print "Usage: ren <filename>"
  sys.exit(1)
  
def startup_hook():
    readline.insert_text(src)

readline.set_startup_hook(startup_hook)

dest = raw_input("Rename to: ")

print
print "Renaming", repr(src), "to", repr(dest)

os.rename(src, dest)
