#!/usr/bin/env python
import readline, sys, os

if len(sys.argv) < 2:
  print "Usage: ren <filename>"
  sys.exit(1)
else:
  srcs = sys.argv[1:]


if len(srcs) > 1:
    print
    print "%d thing(s) to rename..." % len(srcs)
    print

for src in srcs:
    
    if not os.path.exists(src):
      print repr(src), "not found."
      sys.exit(2)
      
    readline.set_startup_hook( lambda: readline.insert_text(src) )
    
    print            "Rename:", src
    dest = raw_input("    to: ")
    print
    
    if src == dest:
      print "Skipping..."
    else:
      print "Renaming", repr(src), "to", repr(dest)
    
    os.rename(src, dest)

    print
