#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "usage: rescan [<file(s) or dir(s)...>]"
  exit 1
fi

if [ "$1" == "" ]; then
  dirs="."
else
  dirs="$@"
fi

echo "* rescanning $dirs"

termux-media-scan -r "$dirs"
