#!/usr/bin/env ruby
require 'epitools'

if ARGV.any?
  files = ARGV.map { |arg| Path[arg].ls }.flatten
else
  files = Path["*"]
end

zeros = files.select{|f| f.size == 0 }

zeros.each { |path| puts path }

if prompt("Remove these files?") == "y"
  puts "Removing files..."
  zeros.each(&:rm)
end

