#!/usr/bin/env ruby

backup = true

exts = %w[c h cpp hpp rb py sh].join(",")

puts "* Recursively stripping trailing whitespace from *.{#{exts}} files..."

Dir["**/*.{#{exts}}"].each do |fn|
  print "  |_ #{fn}"
  
  data = File.read(fn)
  count = 0
  
  stripped_lines = data.each_line.map do |line|
    stripped_line = line.rstrip
    count += 1 unless stripped_line == line.chomp
    stripped_line
  end

  stripped_lines << "" if data[-1] == "\n" # newline at end of file
  stripped_data = stripped_lines.join("\n")

  if data != stripped_data
    puts " (#{count} lines stripped)"
    File.rename(fn, "#{fn}~") if backup
    File.write(fn, stripped_data)
  else
    puts
  end
end
