#!/bin/bash

if [ "$TMPDIR" != "" ] && [ -d $TMPDIR ]; then
  # all is well!
  true
elif [ -d /tmp ]; then
  TMPDIR=/tmp
else
  echo "Error: couldn't find '/tmp', and TMPDIR isn't set; please fix one of these issues and try again!"
  exit 1
fi

CONF=$TMPDIR/rsyncd.conf

echo "---------($CONF)---------"
tee $CONF <<- EOF
	address=0.0.0.0
	port=1873

	[root]
	path = $PWD
	use chroot = false
	read only = false
EOF
echo "---------($CONF)---------"

echo
echo "* starting rsync daemon..."
echo
rsync -vv --daemon --no-detach --config=$CONF --log-file=/proc/self/fd/2
