#!/usr/bin/env ruby

def which(bin)
  ENV["PATH"].split(":").each do |dir|
    full_path = File.join(dir, bin)
    return full_path if File.exists? full_path
  end
  nil
end

opts, args = ARGV.partition { |arg| arg =~ /^-\w/ }

# expand smashed-together options (ie: -alp) into individual options (ie: -a -l -p)
opts = opts.map do |opt|
  if opt =~ /^-(\w{2,})/
    $1.chars.map { |c| "-#{c}" }
  else
    opt
  end
end.flatten.uniq

SSH_ARG_REGEXP = /^([^@]+)@([^:]+):(.+)$/

if args.any?

  unless which("rsync")
    $stderr.puts "rsync not installed. please fix!"
    exit 1
  end

  letters  = %w[r l t]
  letters += %w[o g p] if opts.delete("-o") # ownership
  letters += %w[z]     if args.any? { |arg| arg =~ SSH_ARG_REGEXP } # enable compression over ssh

  params = ["--xattrs"]; opts.delete("-x") # Always sync xattrs

  unless opts.delete "-q"
    params  << "--progress"
    letters << "v"
  end

  params << "--bwlimit=40"      if opts.delete "-l"  # limit bandwidth
  params << "--append-verify"   if opts.delete "-a"  # append to smaller destination files if they match
  params << "--partial"         if opts.delete "-p"  # partials
  params << "--delete-after"    if opts.delete "-d"  # delete destination files
  params << "--dry-run"         if opts.delete "-n"  # simulated sync (no changes are made)
  # params << "--xattrs"          if opts.delete "-x"  # sync extended attributes
  params << "--remove-source-files"   if opts.delete "-m" # move files (delete source files)
  params += ["-e", "ssh -c blowfish"] if opts.delete "-f" # fast cipher
  params += %w[--specials --devices]  if opts.delete "-s" # sync special files (sockets, fifos) and devices

  if opts.delete "-b" # binary mode
    params += ["--checksum", "--copy-links"]
  else
    params << "--size-only"
  end

  params += opts # pass through remaining arguments to rsync
  params += args # ...and the source/destination

  cmd = ["rsync", "-#{letters.join ''}"] + params

  puts "Executing:"
  puts "\t#{cmd.join ' '}"
  puts

  system *cmd

else

  puts "usage: rsync-dirs [options] <src> <dest>"
  puts
  puts "Special options:"
  puts "    -q    Quiet mode"
  puts "    -b    Binary rsync (and dereference symlinks)"
  puts "    -o    Preserve ownership (user/group/permissions)"
  puts "    -s    Sync special files (sockets, fifos, devices)"
  # puts "    -x    Preserve xattrs"
  puts "    -a    Append to smaller destination files"
  puts "          (if their overlap has the same checksum)"
  puts "    -d    Delete destination files that aren't in the source"
  puts "    -m    Move files"
  puts "    -p    Keep partially-transferred files"
  puts "    -n    Dry run (simulated, don't make any changes)"
  puts "    -l    Limit bandwidth to 40k/sec"
  puts "    -f    Fast crypto cipher (arcfour)"
  puts

end
