#!/usr/bin/env ruby

# Creates a webserver on port 8888 for the current dir (or optionally, the directory passed on the commandline)

require 'rack'

# Defaults
port = 8888
root = Dir.pwd

# Parse commandline arguments (root dir or port)
ARGV.each do |arg|
  if arg =~ /^\d{2,5}$/
    port = arg.to_i
  else
    if File.directory? arg
      root = arg
    else
      puts "Error: #{arg.inspect} is not a directory."
      exit 1
    end
  end
end

directory_viewer = proc do |env|
  req = Rack::Request.new(env)

  # Show "index.html" if it exists
  req.path_info += "index.html" if File.exists?(File.join(root, req.path_info, "index.html"))

  # Serve the file or directory
  Rack::Directory.new(root).call(env)
end

puts
puts "* Serving files in: #{root}"
puts "                on: http://localhost:#{port}/"
puts

server = Rack::Handler.pick ['thin', 'webrick']
server.run directory_viewer, Port: port