#!/bin/bash
if [ "$*" == "" ]; then
  echo "usage:"
  echo "  sleepsort 5 3 6 3 6 2 3 1 4 7"
  exit 1
fi

function f() {
    sleep "$1"
    echo "$1"
}
while [ -n "$1" ]
do
    f "$1" &
    shift
done
wait

