#!/usr/bin/env ruby
############################################################
#
# SomaFM XSPF Generator
#
############################################################

require 'open-uri'
require 'json'

def pls_urls(pls)
  URI.open(pls).read.scan(/^File\d+=(.+)$/).flatten
end

puts "========================================="
puts " SomaFM Playlist Generator"
puts "========================================="
puts
puts "* Connecting to API..."

json = JSON.parse(URI.open("https://api.somafm.com/channels.json").read)
puts "  |_ #{json["channels"].size} stations found"
puts
puts "* Writing stations to 'somafm.xspf'..."

channels = json["channels"].sort_by { |ch| -ch["listeners"].to_i }

outfile = open("somafm.xspf", "w")

outfile << %{<?xml version="1.0" encoding="UTF-8"?>
<playlist version="1" xmlns="http://xspf.org/ns/0/">
  <title>SomaFM</title>
  <trackList>
}

channels.map do |ch|
  pls   = ch["playlists"].first["url"]
  url   = pls_urls(pls).first
  title = ch["title"]
  listeners = ch["listeners"]

  puts "  |_ #{title} (#{url}) => #{listeners} listeners"

  outfile << %{
    <track>
      <location>#{url}</location>
      <creator>#{title}</creator>
    </track>
  }
end

outfile << %{
  </trackList>
</playlist>
}

outfile.close
puts
puts "* Done!"
