#!/usr/bin/env ruby
########################################################
require 'epitools'

gem 'slop', "~> 3.6"
require 'slop'
########################################################

########################################################
# Parse options

opts = Slop.parse(help: true, strict: true) do
  banner "Usage: spotify-info [options] <spotify url(s)>"

  # on "a",  "along",  "desc"
  # on "b=", "blong",  "desc", default: ""
end

args = ARGV
# args << "https://open.spotify.com/track/0cCYkGYSndtiSYnBUkJ2iU?si=YS-wwAJlRWmzpox7FncQnQ" if args.empty?

########################################################

def parse_json(json)
  case json["type"]
  when "track"
    {
      title:       json["name"],
      artist:      json["artists"].map { |i| i["name"] }.join(", "),
      album:       json["album"]["name"],
      thumbnail:   json["album"]["images"].sort_by { |i| i["height"] }.last["url"],
      length:      json["duration_ms"].to_i / 1000.0,
      preview_url: json["preview_url"],
    }
  when "album"
    {

    }
  end
end

args.each do |arg|

  html = cached_curl(arg)
  page = Oga.parse_html(html)
  #js   = page.css("script").find { |e| e.text["Spotify.Entity"] }.text
  json = page.at_css("script[type='application/ld+json']").inner_text.from_json

=begin
{"@context"=>"http://schema.googleapis.com/",
 "@type"=>"MusicRecording",
 "@id"=>"https://open.spotify.com/track/1qIi47n0nsdGRfrTe0y57y",
 "url"=>"https://open.spotify.com/track/1qIi47n0nsdGRfrTe0y57y",
 "name"=>"My Agenda (feat. Village People & Pussy Riot) [Anamanaguchi Remix]",
 "description"=>
  "Listen to My Agenda (feat. Village People & Pussy Riot) [Anamanaguchi Remix] on Spotify. Dorian Electra · Song · 2021.",
 "datePublished"=>"2021-11-05",
=end

  json.delete("potentialAction")
  json.delete("@id")
  json.delete("@context")

  pp json

  json = page.css("script[type='application/json']").map{|s| s.inner_text.from_json }.find { |e| e.is_a?(Hash) and e["entities"] }

=begin
{"spotify:track:1qIi47n0nsdGRfrTe0y57y"=>
  {"id"=>"1qIi47n0nsdGRfrTe0y57y",
   "name"=>"My Agenda (feat. Village People &amp; Pussy Riot) [Anamanaguchi Remix]",
   "uri"=>"spotify:track:1qIi47n0nsdGRfrTe0y57y",
   "__typename"=>"Track",
   "album"=>
    {"name"=>"My Agenda (Deluxe)",
     "coverArt"=>
      {"sources"=>
        [{"url"=>"https://i.scdn.co/image/ab67616d0000b27307adcf3680f1962bde42dc3b", "width"=>640, "height"=>640},
         {"url"=>"https://i.scdn.co/image/ab67616d00001e0207adcf3680f1962bde42dc3b", "width"=>300, "height"=>300},
         {"url"=>"https://i.scdn.co/image/ab67616d0000485107adcf3680f1962bde42dc3b", "width"=>64, "height"=>64}]},
     "copyright"=>{"items"=>[{"type"=>"C", "text"=>"2021 Dorian Electra"}, {"type"=>"P", "text"=>"2021 Dorian Electra"}]},
     "date"=>{"year"=>2021},
     "uri"=>"spotify:album:1G5F0OJpuuVZ8g3zw3BMEQ"},
   "artists"=>
    {"items"=>
      [{"id"=>"202HZzqKvPsMHcbwnDZx7u",
        "uri"=>"spotify:artist:202HZzqKvPsMHcbwnDZx7u",
        "profile"=>{"name"=>"Dorian Electra"},
        "visuals"=>
         {"avatarImage"=>
           {"sources"=>
             [{"url"=>"https://i.scdn.co/image/ab6761610000e5eb60857c01dc846983c3aa7d18", "width"=>640, "height"=>640},
              {"url"=>"https://i.scdn.co/image/ab6761610000f17860857c01dc846983c3aa7d18", "width"=>160, "height"=>160}]}},
=end
  items = json.dig("entities", "items")
  items.each { |k,v| pp v }
end

# require 'pry'; binding.pry
