#!/usr/bin/env ruby
require 'rubygems'
require 'epitools'

if ARGV.size < 1 or not ARGV.first =~ /^\w+@[\w\.]+$/
  puts "usage: ssh-authorize user@host"
  puts
  puts "(Copies your id_rsa.pub to the authorized_hosts file of the remote machine.)"
end

userhost = ARGV.first

def get_keys
  Path["~/.ssh/id_{rsa,dsa}.pub"]
end

if get_keys.empty?
  puts "* Generating new SSH key..."
  system "ssh-keygen"
end

get_keys.each do |key|
  puts "* Adding #{key} to #{userhost}:.ssh/authorized_keys"
  #system %{ cat #{key} | ssh #{userhost} 'cat >> ~/.ssh/authorized_keys; cat ~/.ssh/authorized_keys | awk "{print $3}"' }
  system %{ cat #{key} | ssh #{userhost} 'cat >> ~/.ssh/authorized_keys; echo -n Number of keys: ; wc -l ~/.ssh/authorized_keys' }
end
