#!/bin/bash

if [ "$1" == "" ]; then
  echo "Purpose:"
  echo "  Open an x11vnc over an SSH tunnel on localhost:5900"
  echo
  echo "Usage:"
  echo "  ssh-vnc user@host"
  echo
  exit 1
fi

USERHOST="$1"
# VNC="x11vnc -display :0.0 -localhost -ncache_cr -ncache 10 -noxdamage"
VNC="x11vnc -display :0.0 -localhost" # -ncache_cr -ncache 10"

ssh -C -t -L5900:localhost:5900 $USERHOST "$VNC" &
sleep 4
# vncviewer -encodings 'copyrect tight zrle hextile' localhost
vncviewer -geometry 1600x800 localhost 

# in case x11vnc doesn't shut down automatically
kill `jobs -p`

