#!/usr/bin/env ruby

require 'epitools'

class Path
  def zopen
    Object.send(:zopen, self)
  end
end

# May 29 09:51:34 fizz sshd[17892]: Did not receive identification string from 173.68.130.138
# Jun  4 04:13:29 Accepted password for epi from ::1 port 32946 ssh2
# Jun  4 02:34:36 Failed password for root from 124.122.204.163 port 57037 ssh2

lesspipe do |less|

  Path["/var/log/{auth.log,auth.log*.gz}"].sort_by(&:mtime).reverse.each do |path|
    path.zopen.reverse_each do |line|
      if line =~ /^((.+\s+){3})(.+) sshd\[(.+)\]: (.+)$/
        date = $1.strip
        pid = $4
        message = $5
        
        if message =~ /(.+) (password|publickey) for (invalid user )?(.+) from (.+) port (.+) (ssh.+)$/
          result = $1
          authtype = $2
          invalid = $3
          user = $4
          ip = $5
          port = $6
          proto = $7

          case result
            when "Accepted"
              color = "light_green"
            when "Failed"
              color = "light_red"
          end
        
          thing = "<grey>[<white>#{date}<grey>] "
          
          if invalid
            thing << "<grey>#{user} " 
          else
            thing << "<#{color}>#{user} "
          end
          
          thing << "<#{color}>#{result.downcase} "
            
          thing << "<grey>(<light_blue>#{ip}</light_blue>)"
          
          thing << " <light_red>SSH1" if proto == "ssh1"
          thing << " <light_yellow>8=m" if authtype == "publickey"
          less.puts thing.colorize
        end
      end
    end
  end
  
end
