#!/usr/bin/env ruby

require 'epitools'

class IO
  def seekend
    seek(0, IO::SEEK_END)
  end
end

class Path

  def zopen
    Object.send(:zopen, self)
  end

  def each_backwards(&block)
    io = self.zopen
    p [:io, io]
    bs = 2000
    
    last_first = nil
    io.seekend
    pos = [io.pos-bs, 0].max
    
    while pos > 0
      p [:pos, pos]
      io.seek(pos)
    
      data = io.read(bs)
      data << last_first if last_first
      
      enum = data.lines
      last_first = enum.next 
      
      data.lines.each do |line|
        yield line
      end
      
      pos = [pos-bs, 0].max
    end
        
  end

end

# May 29 09:51:34 fizz sshd[17892]: Did not receive identification string from 173.68.130.138
# Jun  4 04:13:29 Accepted password for epi from ::1 port 32946 ssh2
# Jun  4 02:34:36 Failed password for root from 124.122.204.163 port 57037 ssh2

Line = Struct.new(:date, :pid, :message)

lesspipe do |less|

  Path["/var/log/{auth.log,auth.log*.gz}"].sort_by(&:mtime).reverse.each do |path|
    path.zopen.reverse_each do |line|
      if line =~ /^((.+\s+){3})(.+) sshd\[(.+)\]: (.+)$/
        date = $1.strip
        pid = $4
        message = $5
        
        if message =~ /(.+) (password|pubkey) for (invalid user )?(.+) from (.+) port (.+) (ssh.+)$/
          result = $1
          authtype = $2
          invalid = $3
          user = $4
          ip = $5
          port = $6
          proto = $7
          
          case result
            when "Accepted"
              color = "light_green"
            when "Failed"
              color = "light_red"
          end
        
          thing = "<grey>[<white>#{date}<grey>] "
          
          if invalid
            thing << "<grey>#{user} " 
          else
            thing << "<#{color}>#{user} "
          end
          
          thing << "<#{color}>#{result.downcase} "
            
          thing << "<grey>(<light_blue>#{ip}</light_blue>)"
          
          thing << " <light_red>SSH1" if proto == "ssh1"
          thing << " <light_cyan>Public Key" if authtype == "pubkey"
          less.puts thing.colorize
        end
      end
    end
  end
  
end