#!/bin/bash

if [ "$1" == "" ]; then
  echo "Purpose:"
  echo "  Open an x11vnc over an SSH tunnel on localhost:5900"
  echo
  echo "Usage:"
  echo "  ssh-vnc user@host"
  echo
  exit 1
fi

USERHOST="$1"

ssh -C -t -L5900:localhost:5900 $USERHOST "x11vnc -display :0.0 -localhost -ncache_cr -ncache 10 -noxdamage" &
sleep 2
vncviewer -encodings 'copyrect tight zrle hextile' localhost:0

# # in case x11vnc doesn't shut down automatically
# kill `jobs -p`