#!/usr/bin/env ruby

ANSI_RE = %r{
  \e
  [ \[()#;? ]*

  (?:
    [0-9]{1,4}
    (?:
      ;[0-9]{0,4}
    )*
  )?

  [0-9A-PRZcf-nqry=><]
}x

ARGF.each_line do |line|
  print line.gsub(ANSI_RE, '')
end