#!/usr/bin/env ruby
gem 'slop', "~> 3.6"
require 'slop'
require 'epitools'

def parse_options
  opts = Slop.parse(help: true, strict: true) do
    banner "Usage: subs [options] <file(s)...>"
    # on "a",  "along",  "desc"
    # on "b=", "blong",  "desc", default: ""
  end

  [opts, ARGV]
end

opts, args = parse_options

if args.empty?
  puts opts
else
  cmd = %w[subliminal download -l en] + args
  p cmd
  system *cmd
end
