#!/bin/bash
SCRIPTS=$(dirname `which bashrc.leet`)

echo "--------------------------------"
echo "Updating $SCRIPTS"
echo "--------------------------------"

pushd $SCRIPTS > /dev/null

echo "* git pull"
echo -n "  |_ "
git pull
echo
echo "* done!"

popd > /dev/null
