#!/usr/bin/env ruby
require 'fileutils'

args = ARGV

if args.empty?
  puts "Usage: swap <filename> <other_filename>"
  puts "       (swaps the names of two files)"
  exit 1
elsif args.size != 2
  puts "Error: You must supply exactly 2 files to swap."
  exit 1
end

args.each do |arg|
  unless File.exists? arg
    puts "Error: #{arg.inspect} doesn't exist."
    exit 1
  end
end

a, b = args

#include FileUtils::Verbose
include FileUtils

puts "Swapping #{a.inspect} and #{b.inspect}..."

tmp = a + ".swapping"

mv a,   tmp
mv b,   a
mv tmp, b
