#!/usr/bin/env ruby
require 'epitools'
require 'open3'

# list windows
wins = WM.windows.map { |w| [w.desktop_id, "#{w.addr} | #{w.title} (#{w.process.command})"]}

# filter/sort
wins.reject! { |desk, w| desk == -1 }
wins.sort!

# create a blob of text for dmenu
data = wins.map { |desk, w| "#{desk} | #{w}" }.join("\n")

# pick a window
picked, status = Open3.capture2("dmenu -i -l 69 -p Type:", :stdin_data=>data)

# switch to it
addr = picked.split(" | ")[1]
system("wmctrl", "-i", "-a", addr)
