#!/usr/bin/env ruby
require 'epitools'
require 'open3'

missing_binaries = false

# check for required binaries
%w[wmctrl dmenu].each do |thing|
  unless Path.which thing
    puts "Missing command: #{thing} (you must install this package first)"
    missing_binaries = true
  end
end

exit if missing_binaries

# list windows
wins = WM.windows.sort_by { |w| [w.desktop_id, w.title] }.map { |w| [w.desktop_id, "#{w.addr} | #{w.title} ::: (#{w.process.command})"]}

# remove non-window windows
wins.reject! { |desk, w| desk == -1 }

# create a blob of text for dmenu
data = wins.map { |desk, w| "#{desk} | #{w}" }.join("\n")

# pick a window
picked, status = Open3.capture2("dmenu -i -l 50 -p Name:", :stdin_data=>data)

if status == 0 # did the user pick something?
  # switch to it
  addr = picked.split(" | ")[1]
  system("wmctrl", "-i", "-a", addr)
end