#!/usr/bin/env ruby
TERMS = %w[terminal xfce4-terminal]

def which(bin)
  ENV["PATH"].split(":").each do |path|
    fullpath = File.join(path, bin)
    return fullpath if File.exists? fullpath
  end
  nil
end

# Find a terminal to use
cmd = [ TERMS.find { |term| which(term) } ]
cmd << "--geometry=90x42"

# Hold terminal after command is finished
cmd << ARGV.shift if ARGV.first == "-H" 

if ARGV.any? 
  # Run a command
  require 'shellwords'
  cmd << "--command=#{Shellwords.shelljoin ARGV}" 
end

# Launch the terminal
exec *cmd
