#!/usr/bin/env ruby

# TODOs: when symlinked as a different filename, it does different things
# - if the filename is "today" or "datestamp", print YYYY-MM-DD
# - if it's "epoch" or "unixtime", print unix epoch
# - if it's "now" or "timestamp", print YYYY-MM-DD HH:MM:SS (nice_stamp)

def usage
  puts DATA.read
end

def nice_stamp
  Time.now.strftime("%Y-%m-%d %H:%M:%S")
end

args = ARGV

if STDIN.tty?
  if args.delete("--help") or args.delete("-h")
    usage
    exit
  elsif args.delete("-n") or args.delete("--nice")
    puts nice_stamp
  else
    puts Time.now.to_i
  end
else
  STDIN.each_line do |line|
    STDOUT.puts "[#{nice_stamp}] #{line}"
    STDOUT.flush
  end
end


__END__
usage:
  $ timestamp
    => print the number of seconds since Jan 1 1970
  $ some command | timestamp
    => print each line of the input, prefixed with "[YYYY-MM-DD HH:MM:SS] "
