#!/bin/bash

#SERVER=time.nist.gov
SERVER=ca.pool.ntp.org


echo Synching clock ...
sudoifnotroot ntpdate $SERVER
echo Setting hardware clock...
sudoifnotroot hwclock --systohc --localtime
#/etc/rc0.d/K25hwclock.sh reload

