#!/bin/bash
if [ -f /usr/bin/tree ]; then
  CMD=/usr/bin/tree
elif [ -f /usr/local/bin/tree ]; then
  CMD=/usr/local/bin/tree
else
  echo "Error: tree command not found"
  exit 1
fi

$CMD -C "$@" | less -SRXFi
