#!/usr/bin/env ruby

class String
  def url?
    match %r{^https?://.+}
  end
end

opts, args = ARGV.partition { |arg| arg[/^--?\w/] }

if args.empty? or opts.include?("-h") or opts.include?("--help")
  puts "usage:"
  puts "  ttm [option] <file or url>"
  puts
  puts "options:"
  puts "  -s   shorten all urls (must supply only urls)"
  exit 1
end

args.each do |arg|
  
  if opts.include?("-s")
    raise "error: can't shorten a file." unless arg.url?
    
    puts "* Shortening: #{arg}"
    form = "shorten=#{arg}"
  else
    if arg.url?
      puts "* Mirroring: #{arg}"
      form = "url=#{arg}"
    else
      puts "* Uploading: #{arg}"
      form = "file=@#{arg}"
    end
  end

  cmd = [
    "curl",
    "--compressed",
    "--progress-bar",
    "-F#{form}",
    "https://ttm.sh"
  ]

  puts IO.popen(cmd, &:read)
  puts
end
