#!/usr/bin/env python

import sys, requests

URL_URBANDICTIONARY = "http://api.urbandictionary.com/v0/define"
HELP = """
purpose:
    Get the definition of a provided term from Urban Dictionary

usage: 
    ud <query> [<result number>]
"""

def err(*args):
    print(*args, file=sys.stderr)

def print_definition(definition):
	print(
	    "%s: %s" % (
	        definition["word"],
	        definition["definition"].
	            replace("\n", " ").
	            replace("\r", "").
	            replace("  ", " ")
	    )
	)
	print()

def ud(args):
    number = 0
    term = args
    if (args[-1].isdigit()):
        number = int(args[-1])
        term = term[:-1]
    term = " ".join(term)

    page = requests.get(URL_URBANDICTIONARY, params={"term": term}).json()

    if page:
        results = page["list"]

        err(f"* Found {len(results)} results...")
        err()

        if len(results):
            if number > 0:
                if len(results) > number-1:
                    definition = results[number-1]
                    print_definition(definition)
                else:
                    err("Definition number does not exist")
            else:
                for definition in results:
                    print_definition(definition)
        else:
            err("No results found")
    else:
        raise "couldn't get the JSON from urbandictionary for some reason"


if __name__ == "__main__":
    args = sys.argv[1:]

    if len(args) > 0:
        ud(args)
    else:
        print(HELP)
