#!/usr/bin/ruby
puts "====================================="
puts "         Underscorize_v_0.000000001"
puts "--------------------------------------"

if ARGV.empty?
 puts "Purpose:"
 puts "    Replace spaces with underscores in filenames."
 puts
 puts "Usage:"
 puts "    underscorize [filenames...]"
 puts
 exit
end

for fn in ARGV
 new_fn = fn.gsub(' ', '_')
 if fn == new_fn
  puts %{ - Skipping "#{fn}"}
 elsif File.exists? fn
  puts %{* Renaming "#{fn}" -> "#{new_fn}"}
  File.rename fn, new_fn
 else
  puts %{! cannot find file: "#{fn}"}
 end
end

puts
