#!/usr/bin/env ruby
clips = %w[primary clipboard].map { |type| `xclip -o -selection #{type}`.chomp }

if clip = clips.find { |c| c[%r{^(https?|magnet):}] }
  exec("#{__dir__}/web", clip)
else
  error_message = "Error: Couldn't find an URL in the clipboard"
  $stderr.puts error_message
  exec("notify-send", error_message)
end
