#!/bin/bash

if [ "$1" == "" ]; then
  echo "usage: wget-google-doc <https://docs.google/com/document/d/<id>/preview>"
  exit 1
fi


# for more formats, see "man rclone" => "Import/Export of google documents"
#FORMAT=pdf
#FORMAT=docx
#FORMAT=md
#FORMAT=epub
#FORMAT=odt
#FORMAT=txt
#FORMAT=rtf
FORMAT=html

if [[ "$1" =~ https://docs.google.com/document/d/([^/]+)/preview ]]; then
  ID="${BASH_REMATCH[1]}"
  OUT="${ID}.${FORMAT}"
  # NOTE: can accept &token= for private docs
  wget "https://docs.google.com/document/export?format=${FORMAT}&id=${ID}&includes_info_params=true" -O "$OUT"
fi
