#!/bin/bash

if [ "$1" == "" ]; then
  echo "usage: wget-google-doc <https://docs.google.com/document/d/<id>>"
  echo
  echo "By default, this script saves the document as an HTML file. You can alter this by setting the FORMAT environment variable."
  echo "(this should be a commandline option, but I'm not super good at bash. sorry!)"
  echo
  echo "Example:"
  echo "  $ FORMAT=pdf wget-google-doc https://docs.google.com/document/d/FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF/edit"
  echo
  echo "Valid FORMATs: html (default), pdf, docx/odt, epub, txt, rtf, xlsx/ods, tsv, csv, jpg, png, svg, pptx/odp, json, zip"
  echo "(for more formats, see 'man rclone', section: 'Import/Export of google documents')"
  echo
  exit 1
fi

if [ -z "$FORMAT" ]; then
  FORMAT=html
fi

if [[ "$1" =~ https://docs.google.com/document/d/([^/]+)/ ]]; then
  ID="${BASH_REMATCH[1]}"
  OUT="${ID}.${FORMAT}"

  # NOTE: accepts &token= for private docs
  wget "https://docs.google.com/document/export?format=${FORMAT}&id=${ID}" -O "$OUT"
  #wget "https://docs.google.com/document/export?format=${FORMAT}&id=${ID}&includes_info_params=true" -O "$OUT"
fi
