#!/bin/bash
BASE="$HOME/.local/share/wineprefixes"

if [ "$1" == "" ]; then
  echo "Usage: wineprefix <prefix name> [command/.exe]"
  echo
  echo "Prefixes are created in '$BASE'"
  echo "(If only a prefix name is passed, it runs 'winecfg' on that prefix)"
  exit 1
fi

if [ ! -d "$BASE" ]; then
  mkdir -p "$BASE"
fi

if [ "$1" == "" ]; then
  find "$BASE" -maxdepth 1
  exit
fi

PREFIX="$BASE/$1"
shift

echo "Prefix: $PREFIX"

if [ ! -d $PREFIX ]; then
  echo "Creating new prefix..."
  mkdir "$PREFIX"
fi

export WINEPREFIX="$PREFIX"

if [ "$1" == "winecfg" ]; then
  winecfg
else
  wine $@
fi
