#!/usr/bin/env ruby
args = ARGV

cmd = %w[xfconf-query --channel=xfwm4 --property=/general/use_compositing]

case args.first
when "on"
  cmd << "--set=true"
  msg = "Compositor on!"

when "off"
  cmd << "--set=false"
  msg = "Compositor off!"

when "toggle"
  state = `#{cmd.join ' '}`

  case state
  when /true/
    cmd << "--set=false"
    msg = "Compositor off!"
  when /false/
    cmd << "--set=true"
    msg = "Compositor on!"
  end

when nil
  puts "usage: xfwm-compositor [on/off/toggle]"
  exit 0
  
else
  puts "unknown argumantes"
  exit 1
end

system("notify-send", msg)
system(*cmd)