#!/bin/bash
#
# use: X [:<display>] [option]
# -a #                   default pointer acceleration (factor)
# -ac                    disable access control restrictions
# -audit int             set audit trail level
# -auth file             select authorization file
# -br                    create root window with black background
# +bs                    enable any backing store support
# -bs                    disable any backing store support
# -c                     turns off key-click
# c #                    key-click volume (0-100)
# -cc int                default color visual class
# -nocursor              disable the cursor
# -core                  generate core dump on fatal error
# -displayfd fd          file descriptor to write display number to when ready to connect
# -dpi int               screen resolution in dots per inch
# -dpms                  disables VESA DPMS monitor control
# -deferglyphs [none|all|16] defer loading of [no|all|16-bit] glyphs
# -f #                   bell base (0-100)
# -fc string             cursor font
# -fn string             default font name
# -fp string             default font path
# -help                  prints message with these options
# +iglx                  Allow creating indirect GLX contexts
# -iglx                  Prohibit creating indirect GLX contexts (default)
# -I                     ignore all remaining arguments
# -ld int                limit data space to N Kb
# -lf int                limit number of open files to N
# -ls int                limit stack space to N Kb
# -nolock                disable the locking mechanism
# -maxclients n          set maximum number of clients (power of two)
# -nolisten string       don't listen on protocol
# -listen string         listen on protocol
# -noreset               don't reset after last client exists
# -background [none]     create root window with no background
# -reset                 reset after last client exists
# -p #                   screen-saver pattern duration (minutes)
# -pn                    accept failure to listen on all ports
# -nopn                  reject failure to listen on all ports
# -r                     turns off auto-repeat
# r                      turns on auto-repeat
# -render [default|mono|gray|color] set render color alloc policy
# -retro                 start with classic stipple and cursor
# -s #                   screen-saver timeout (minutes)
# -seat string           seat to run on
# -t #                   default pointer threshold (pixels/t)
# -terminate             terminate at server reset
# -to #                  connection time out
# -tst                   disable testing extensions
# ttyxx                  server started from init on /dev/ttyxx
# v                      video blanking for screen-saver
# -v                     screen-saver without video blanking
# -wm                    WhenMapped default backing-store
# -wr                    create root window with white background
# -maxbigreqsize         set maximal bigrequest size
# +xinerama              Enable XINERAMA extension
# -xinerama              Disable XINERAMA extension
# -dumbSched             Disable smart scheduling and threaded input, enable old behavior
# -schedInterval int     Set scheduler interval in msec
# -sigstop               Enable SIGSTOP based startup
# +extension name        Enable extension
# -extension name        Disable extension
# -query host-name       contact named host for XDMCP
# -broadcast             broadcast for XDMCP
# -multicast [addr [hops]] IPv6 multicast for XDMCP
# -indirect host-name    contact named host for indirect XDMCP
# -port port-num         UDP port number to send messages to
# -from local-address    specify the local address to connect from
# -once                  Terminate server after one session
# -class display-class   specify display class to send in manage
# -cookie xdm-auth-bits  specify the magic cookie for XDMCP
# -displayID display-id  manufacturer display ID for request
# [+-]accessx [ timeout [ timeout_mask [ feedback [ options_mask] ] ] ]
#                        enable/disable accessx key sequences
# -ardelay               set XKB autorepeat delay
# -arinterval            set XKB autorepeat interval
# -display string        display name of the real server
# -sync                  sinchronize with the real server
# -full                  utilize full regeneration
# -class string          default visual class
# -depth int             default depth
# -sss                   use software screen saver
# -geometry WxH+X+Y      window size and position
# -bw int                window border width
# -name string           window name
# -scrns int             number of screens to generate
# -install               instal colormaps directly

# [mi] Available extensions:
# [mi]    Generic Events
# [mi]    DAMAGE
# [mi]    DOUBLE-BUFFER
# [mi]    GLX
# [mi]    MIT-SCREEN-SAVER
# [mi]    RANDR
# [mi]    RENDER
# [mi]    SECURITY
# [mi]    X-Resource
# [mi]    XFIXES
# [mi]    XINERAMA
# [mi]    XTEST
# [mi]    XVideo


res=1400x900
disp=:1

Xnest +extension GLX +extension XVideo +extension DOUBLE-BUFFER +extension RENDER +extension SECURITY -geometry $res $disp &

if [ "$0" != "" ]; then
  sleep 0.4
  DISPLAY=$disp $@
  kill `jobs -p`
fi
