#!/usr/bin/env python3
#
# Goal: Replace youtube-dl with this, and it'll go faster (by keeping a copy running in the background that it talks to)
# (not finished)
#
# TODOs:
# - daemonize
# - create a socket to read JSON blobs from the client
#   => { pwd: <client's pwd>, args: <ytdl args> }
# - create a client
# - make a dumb cmd.Cmd CLI for testing
#
import sys
import os
import readline

realexit = sys.exit
sys.exit = lambda n: print("they wanted me to die (%d) BUT I REFUSED" % n)

current_dir, _ = os.path.split(sys.argv[0])
sys.path.append(current_dir+"/src/yt-dlp")
print("* loading all the crap...")
import yt_dlp
print("  |_ done!")

try:
  while True:
    #print("hit me > ", end="", flush=True)
    cmd = input("hit me > ").strip()
    if len(cmd) > 0:
      args = cmd.strip().split()
      yt_dlp.main(args)
      print("that was fun! let's go again!")
except (KeyboardInterrupt, EOFError):
  print("ok, fine")
  realexit(0)
