#!/usr/bin/env ruby
gem 'slop', "~> 3.6"
require 'slop'
require 'epitools'

def parse_options
  opts = Slop.parse(help: true, strict: true) do
    banner "Usage: zbaq [options] <destination> <dirs>"

    # on 'c',  'codecs',  'List the availiable codecs'
    # on 'u=', 'use',     'Tool to use (ffmpeg, mencoder)', default: "ffmpeg"
  end

  [opts, ARGV]
end

opts, args = parse_options

# Do stuff here
destination, *sources = args

unless destination and sources.any?
  puts opts
  exit 1
else
  puts "* Writing BAQUP to #{destination} using #{sources}"

  cmd = ["zpaq", "add" , "#{destination}???", *sources, "-index", "#{destination}.zpaq"]
  p cmd
  if system *cmd
    system "ls", "-lhv", *Dir["#{destination}*"]
  else
    puts "ERRORN!!!!!!!!!!!!!!!!".light_red
    exit 1
  end
end
