#!/usr/bin/env ruby

require 'epitools'

for arg in ARGV
  f = Path[arg]
  puts "* #{arg} (#{f.size.commatize} bytes)"
  unless f.size > 0
    puts "  |_ Already deleted..."
    next
  end

  f.rename!(filename: "#{f.filename}.deleted")
  puts "  |_ #{f.filename}"
  f.open("wb") { }
end


