#!/bin/bash
if [ "$1" == "--help" ]; then
  echo "usage: f <expr> [dirs...]"
  exit
fi

expr="$1"
shift

if [ "$#" == "0" ]; then # no directories specified
  find -x . | ag "$expr" # grep -Ei --color=always "$expr"
else
  while (( "$#" )); do   # for each directory
    find -x "$1" | ag "$expr"  #grep -Ei --color=always "$expr"
    shift
  done
fi
