#!/bin/bash
if [ "$1" == "--help" ]; then
  echo "usage: f <expr> [dirs...]"
  exit
fi

expr="$1"
shift

if [ "$#" == "0" ]; then
  find -x . | grep -Ei --color=always "$expr"
else
  while (( "$#" )); do
    find -x "$1" | grep -Ei --color=always "$expr"
    shift
  done
fi
